config/routes.rb
Rails.application.routes.draw do
  get 'info/about'

  get 'info/privacy'

  get 'info/license'

  get 'info/home'

  get 'info/join'

  get 'info/team'

  devise_for :users 
  resources :locks
  resources :infos

  root 'info#home'
end

app/models/info.rb
class Info < ActiveRecord::Base
end

app/models/kind.rb
class Kind < ActiveRecord::Base
  has_many :locks
end

app/models/lock.rb
class Lock < ActiveRecord::Base
  belongs_to :kind

  validates :name , presence: true
  validates :website , presence: true
  validates :username , presence: true
  validates :password , presence: true

  def self.search(search)
  	where("name LIKE ?", "%#{search}%")
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

end

app/controllers/info_controller.rb
class InfoController < ApplicationController
	
  def about
  end

  def privacy
  end

  def license	 	 
  end

  def home
  end
  
  def join
  end

  def team
  end

  
 
end

app/controllers/locks_controller.rb
class LocksController < ApplicationController
	before_action :authenticate_user!
	def index
		@lock = Lock.all 
		if params[:search]
			@lock = Lock.search(params[:search]).order("created_at DESC")
		else
			@lock = Lock.all.order('created_at DESC')
		end
	end

	def show
		@lock = Lock.find_by_id(params[:id])
	end

	def new
		@lock = Lock.new
	end

	def create
		@lock = Lock.create(lock_params)
		if @lock.save
			flash[:notice] = "Account was  Successfully saved"
			redirect_to locks_path
		else
			flash.now[:error] = "Something went wrong! Please try again!"
			render :new
		end
	end

	def update
		@lock = Lock.find_by_id(params[:id])
		if @lock.update(lock_params)
			flash[:notice] = "Account was Successfully updated"
			redirect_to locks_path
		else
			flash.now[:error] = "There was  a problem updating this  account"
			render :edit
		end
	end

	def edit
		@lock = Lock.find_by_id(params[:id])
	end

	def destroy
		@lock = Lock.find_by_id(params[:id])
		@lock.delete
		redirect_to locks_path
	end

	private

	def lock_params
		params.require(:lock).permit(:name, :website, :username, :password, :additional_info, :email_linked_with_this_account, :kind_id, :search)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/info_helper.rb
module InfoHelper
end

app/views/info/about.html.erb
<div id="a">
           
<h1>About  DataIn  website</h1><br>
<p>This  is  an  aplication  that  helps  you    save  all  your  usernames  and  passwords  of  diffrent  accounts  that  you  have online.</p>

<p>Most  of  the  time,  if  you  don't  use  that  account  for  more  than  50  days,  studies  show  that  there  is  a  high  chance you  will  forget  it,  and  if  you  didn't  save  that  information  somewhere,  then  you  have  to  go from the  long  and  boring  process  to  ask  for  a  new  username  and  password.</p>

<p> This  application  will  help  you  avoid  all  that  waste of  time  by  just  opening  DataIn  account   and  find  the  account  and  password  you  need  in  DataIn  database.</p>

<P>Now  your  are  thinking... How  it  works? The  way  This  application  works  is  very  simple. You  need   to  create  an  account  by  answering  all  the  questions  it  asks. You  need  to  choose an  stong  username  and  password,  that  are  very  hard  to  get  memorized  from  other  people  who  want  to  access  your  database.</P>

<p>Also you  need  to  remember  these  username  and  password,  if  you  don't  want  to  go  through  the  long  process  to  change  them.</p>
<br>
<p>Is  this  application  safe?  How  safe is  your  sensitive  information in  this  application? When  it  comes  to  security  of  your  information,  this  application  takes  it  very  seriously. Our  service  is  to  keep  safe  your  information,  and  we  have  invested  a  lot  at  this  point.  Also, your  password  and  username  can't  be  accessed by  poeple  that  manage  the  application  becasuse  it  encrypts  all  that  information  and  can't  be  unencrypted.  The  only  way to  access  your  information  is  by  entering  the  write  username  and  password  that  you  have  assigned  with  that  account. So,  the  only  one  that  can  access  your account  is  you,  which  means  that your  database  is available  only  to  you  and  no one  inside  or  outside  the  company  can  access  it.</p>
<br>
<p>How  can  I  use  it?  It  is  also  very  simple.  You  need  to  open  your  DataIn  account, go  to accounts  and  click  the  add  account  button. It  will  open  a  new  page  where  you  have  to   enter  information  about  that  account,  like : username, Password, website, info  etc. and  then  click   create. When  you  go  to the  accounts  page,  it  will  be  available immediately at  that  database. You can  access  DataIn  anytime  you  need  information  about  that  account.It  is  highly  recommended  when  you  open  a  new  account  online,  you  should also  register  that  account in DataIn website in  order  to  have  it  in  your  database  anytime  you  want.</p>
<br>
<p>DataIn  Will  help  you  make  your  life  simple,  thats why  we  created  it!</p>

<p>Thank you!</p>
<hr>
</div>

app/views/info/home.html.erb
<%= stylesheet_link_tag "style.css" %>
<body>
<div style="margin: 0 auto;
            width: 80%;
            height: 900px;
            ">
            

 <div style="width:900px;
             height:270px;
             margin: 0 auto;          
             text-align: center;
             font-size: 50px;
             background-color: grey;
             opacity: 0.3;
             border-radius: 30px;">

             <p style="font-size: 65px;">DataIN</h1>
             <p>Save  your memory for more  important things</p>
  </div>

     <div style="width: 40%;
                 height: 550px;
                 margin: 0px;
                 margin-top: 30px;
                 display: inline-block;
                 color: violet;
                 opacity: 0.7;
                 ">
                 <h1>This  website  will  help  you  manage  your  online  accounts, keeping  them  secure  and  accessable  anytime</h1><br>
                 <h1>For  more  information  click  at  About us link  and  open  an  account  for  free</h1><br>
                 <h1>Thank  you  for  your time!</h1>
  </div>

   <div style="margin-right: 200px;
               margin-top: 100px;
               width:300px;
               height: 300px;
               text-align: center;
               color: black;
               float: right;
               background: rgba(255,255,255,0.5);
               border-radius: 40px;
               border-color: 2px violet;
               padding: 10px;
              ">
           <ul style=" padding-right: 50px;list-style-type: none;">  
           <% if current_user %>  
           <li><h2>Save your  accounts by clicking  the  below button!</h2></li>         
           <li><button class="button"><%= link_to "Save", new_lock_path %> </button></li>
          <% else %>
              <li><h2>Don't have  an  account  with  us?</h2></li>
              <li><h2>Please  register!</h2></li>
              <li><button class="button"><%= link_to "Register", new_user_registration_path %> </button></li>
          <% end %>                 
            </ul>
        </div>
            
   </div>
   
</body>

app/views/info/join.html.erb
<div style="margin: 0 auto;
            width: 80%;
            height: 100%;">
            <div style="margin: 50px 0 0 0;
                        border: 3px violet;
                        border-radius: 30px;
                        padding: 30px;
                        width: 80%;
                        background:rgba(90,90,90,0.3);
                        color: black;
                        font-size: 25px;
                        font-family: 'calibri';">
  <h1>Thank  you  for  your interest  in  DataIN</h1>
  <br>
  <div class="p"><hr>
  <p>We  don't  have  any  available  positions  right  now</p>
  <p>but,  don't  get  discurieged</p>
  <p>You  can  send  your  resume directly  to  our  email  address, so  we  save  it  in  our  database  and  if  we  need  help  in  the  future,  we  will  contact  you immediately.</p>

  <p> Right  now  we  are  looking  for  professionals  who  want  to participate  in  our projects  we  want  to  build  in  the  future.</p>
  <p> This  is  a  good  possibility  for everyone  who  wants to  extend  his/her  experience  in  software  and  web  Development.</p>

  <p>If  this  sounds  good  to  you,  please  shoot  us  an  email</p>

  <p>We  will  respond  as  soon  as  possible</p>
  <p>For  contact  information  please  visit  Contact Us  page</p>

  <p>Wish  you  a  lovely  rest  of  the  day  and  happy  coding</p>

  <p>Thank  you !</p>  
  <hr>
  </div>
            </div>
</div>

app/views/info/license.html.erb
<div style="margin: 0 auto;
            width: 80%;
            
            border: 3px violet;
            border-radius: 30px;
            padding: 30px 0px 30px 100px;
            font-size: 30px; 
            background:rgba(90,90,90,0.3);
            color: black;
            font-family: 'calibri';">
                 
            <h1 style="font-size: 35px;"><strong>welcome  to  contact  page</strong></h1><br>
            <h2 style="font-size: 25px;">In  order  to  serve  you  better,  please send  
            us  your  comments directly.</h2><br>

            <p style="font-size: 20px;">Telephone number : 45454545</p>
            <p style="font-size: 20px;">Address :  2348 82nd street, Brooklyn ,
                          NY,  11214</p>
            <p style="font-size: 20px;">Email  address: datain@FKsolutions.com</p> <br>

            <p> If  you  have  concearns  or  issues  using  this  website,  you  are  welcome  to  write  us  anytime. We  are  glad  to  assist you!</p>
            <p> Thank You!</p> <hr>
      </div>

app/views/info/privacy.html.erb
<div style="margin: 0 auto;
            width: 80%;
            height: 900px;
            background-image: url(../images/12.jpg);
            background-repeat: no-repeat;
            background-size: cover;">
<h1>Info#privacy</h1>
<p>Find me in app/views/info/privacy.html.erb</p>
</div>

app/views/info/team.html.erb
<div style="margin: 0 auto;
            width: 80%;
            height: 100%;">
            <div style="margin: 50px 0 0 0;
                        border: 3px violet;
                        border-radius: 30px;
                        padding: 30px;
                        width: 80%;
                        height: 750px;
                        background:rgba(90,90,90,0.3);
                        color: black;
                        font-size: 25px;">
     <h1 style="text-align: center; font-family: 'centry'; color: white;"> Founder </h1> <hr>
             <div style="width: 300px;
                        height: 400px;
                        border-radius: 50px;
                        background-image: url(../images/Fatjon.jpg);
                        background-repeat: no-repeat;
                        background-size: cover;
                        display: inline-block;">
                        </div>

     <div style="height: 600px;
                 width: 550px;
                 margin-right: 10px;
                 font-size: 20px;
                 font-family: 'calibri';
                 color: white;
                 float: right;
                 ">
        <h2 style="text-align: center;"> Fatjon Kerxhaliu </h2>
        <h4 style="text-align: center;">Software Developer  |  New York City </h4>
        <hr style="width: 300px; margin-left: 125px;">

        <h2> About </h2>
        <p> Fatjon is  a  IT  specialist  interested  in  Software  and  web Development. He  develops  websites  and  softwares  using  mostly  Ruby on Rails, Java  and  Html, CSS, Javascript. Most  of  the  time he  is  working  on  his  online  projects  or  websites and  in  his  free  time  he  likes to  travel  or  cycling. His  favorite expression  is :" Don't tell  me  how much  you know but tell me how  many  places  have  you  visited" ( Unknown Author), and  he  tries  to get  a piece  of  each  place  he  visits. 
        <p> Liberal  and  agnostic </p> 
        <hr style="width: 300px; margin-left: 125px;">
                    </div>
            </div>
</div>

app/views/layouts/_navigation.html.erb
<header class="navbar navbar-inverse">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
        <div class="navbar-brand" style="width: 1200px;">
          <ul class="ul">
                                
            <li class="li">  <%= link_to 'Home', info_home_path %></li>
            <li class="li">   <%= link_to 'Accounts', locks_path %></li>
            <li class="li">   <%= link_to 'Create', new_lock_path %></li>
            <li class="li">   <%= link_to 'About Us', info_about_path %></li>
            <li class="li">   <%= link_to 'Contact Us', info_license_path %></li> 
             <%= form_tag(locks_path, :method => "get", id: "search-form") do %>
               <%= text_field_tag :search, params[:search], placeholder: "Search name" , class: 'nav_search'%>
               <%= submit_tag "Search" %>
          <% end %>
           </ul>
        </div>
    </div>
   

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
          <li><strong><%= current_user.first_name %></strong></li>
          <li><%= link_to "Sign out", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Log in", new_user_session_path %> </li>
          
        <% end %>

      </ul>
    </div><!-- /.navbar-collapse -->

  </div><!-- /.container-fluid -->
</header>

 



app/views/layouts/_navigationFooter.html.erb
<%= stylesheet_link_tag "style.css" %>
<footer>
<div class="footer">
  <div class="footer-items-hold">
    <div class="links">
      <%= link_to 'Join Us', info_join_path %> |  <%= link_to 'Team', info_team_path %><br>
      
    </div>
    <div class="footer-text">
      <p>DataIN  is  developed  in 2016  by  Fatjon Kerxhaliu.Some  fo  the  images used  in  this  website  are  taken  through different  sources  with  their  permission</p>
    </div> 
    <div class="media">
    <%= link_to image_tag('social-fb.jpg'), "http://www.facebook.com/"%>
    </div><div class="media">
    <%= link_to image_tag('social-tw.jpg'), "http://www.twitter.com/"%></div><div class="media", style="background-size: cover;">
    <%= link_to image_tag('social-ln.jpg'), "http://www.linkedin.com/"%>
    </div>
  </div>
</div>
</footer>

app/views/layouts/_notification.html.erb
<% flash.each do |name, msg| %>
  <div class="alert alert-<%= name == 'notice' ? 'success' : 'danger' %>" >
    <%= msg %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag "style.css" %>
  </head>
  <body>
  
    <%= render 'layouts/navigation' %>
    
        <%= render 'layouts/notification' %>
      <%= yield %>
   
     <%= render 'layouts/navigationFooter'%>
     
   
  </body>
</html>

app/views/locks/_form.html.erb

  <%= form_for @lock, html: { multipart: true} do |f| %>

  <% if @lock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lock.errors.count, "error") %> prohibited this account from being saved:</h2>

      <ul>
      <% @lock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  

  <div class="input-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control',  placeholder:'Account Name' %>
  </div><br>

  <div class="input-group">
    <%= f.label :website %><br>
    <%= f.text_field :website, class: 'form-control', placeholder: 'https://example.com/users/'%>
  </div><br>


  <div class="input-group">
    <%= f.label :username %><br>
    <%= f.text_field :username, class: 'form-control',  placeholder:'Username' %>
  </div><br>

   <div class="input-group">
    <%= f.label :password %><br>
    <%= f.text_field :password, class: 'form-control',  placeholder:'Password'%>
  </div><br>

  <div class="input-group">
    <%= f.label :additional_info %><br>
    <%= f.text_area :additional_info, class: 'form-control',  placeholder:'Add info' %>
  </div><br>

  <div class="input-group">
    <%= f.label :email_linked_with_this_account %><br>
    <%= f.text_field :email_linked_with_this_account, class: 'form-control',  placeholder:'Add email' %>
  </div><br>

  <p>
    <%= f.label :kind %><br>
    <%= collection_select(:lock, :kind_id, Kind.all, :id, :name, include_blank: true) %>
  </p><br>


  <%= f.submit %>
 
<% end %>

app/views/locks/edit.html.erb
<div style="margin: 0 auto;
            width: 80%;
            height: 100%;">
            <div style="margin: 50px 0 0 0;
                        border: 3px violet;
                        border-radius: 30px;
                        padding: 30px;
                        width: 50%;
                        background:rgba(90,90,90,0.3);
                        color: black;">
    <h1>Edit Account</h1>

    <%= link_to "Back to Account list", locks_path %>
​
   <%= render 'form' %>
  </div>
</div>



  

app/views/locks/index.html.erb
<div style="margin: 0 auto;
            width: 80%;
            height: 300%;
            
            padding: 10px;">
   <div class="row">
      <div style="width: 960px;
                  height: 500px;             
                  background: rgba(255,255,255,0.3);
                  border-radius: 40px;
                  border-color: 2px violet;">
         <h1 style="text-align: center;padding-top: 50px;">Accounts  List</h1>
          <div style=" width:400px;
                       height: 250px;
                       margin-top: 50px; 
                       margin-left: 20px; 
                       color: white;
                       border-radius: 40px;
                       border-color: 2px violet;
                       background: rgba(255,255,255,0.5);
                       padding: 20px;
                       display: inline-block;">
              <button class="btn btn-lg btn-danger" style="margin-left: 50px;" ><%= link_to  "Create New account", new_lock_path %></button><br><br>
  
              <p class="p"> You  can  search  your  account  by  name </p>
              <%= form_tag(locks_path, :method => "get", id: "search-form") do %>
                <%= text_field_tag :search, params[:search], placeholder: "Search name" , class: 'search1' %>
                <%= submit_tag "Search" , class: 'search' %>
             <% end %>
         </div>
         <div style="width: 400px;
                     height: 250px;
                     color: black;
                     font-family: 'calibri';
                     margin-top: 50px;
                     margin-left: 100px;
                     display: inline-block;
                     font-size: 30px;">
              <p> This  is your  accounts  list  with  their  sensitive  information!</p>
              <P> Please  don't  forget to  <strong>Sign Out</strong>  after  you  are  done  with  the  website.</P> </div>
        </div>
      </div>

      <div style="width: 95%;padding: 10px;">
    <table>
      <tr>
        <th class="table2">Name</th>
        <th class="table2">Website</th>
        <th class="table2">Username</th>
        <th class="table2">Password</th>
        <th class="table2">Kind</th>
        <th class="table2"></th>  
      </tr>
      <tbody>
      <% @lock.each do |lock| %>
        <tr>
          <td class="table1"><%= link_to lock.name, lock_path(lock) %></td>
          <td class="table1"><%= lock.website %></td>
          <td class="table1"><%= lock.username %></td>
          <td class="table1"><%= lock.password %></td>
          <td class="table1"><%= lock.kind.try(:name) %></td>
          <td class="table1"><%= link_to "edit", edit_lock_path(lock) %> | 
          <%= link_to "delete", lock_path(lock), method: :delete, data: {confirm: "Are you sure you want to delete this account?"} %>
          </td><br>
        </tr>    
      <% end %>
      </tbody>
    </table>
  </div>

</div>


app/views/locks/new.html.erb
<div style="margin: 0 auto;
            width: 80%;
            height: 100%;">
            <div style="margin: 50px 0 0 0;
                        border: 3px violet;
                        border-radius: 30px;
                        padding: 30px;
                        width: 50%;
                        background:rgba(90,90,90,0.3);
                        color: black;">
<h1>Add Account</h1>

<%= link_to "Back to Account list", locks_path %>

​
<%= render 'form' %>

</div>
</div>



 
    

app/views/locks/show.html.erb
<%= stylesheet_link_tag "style.css" %>
<div style="margin: 0 auto;
            width: 80%;
            height: 100%;
            border: 3px violet;
            border-radius: 30px;
            padding: 30px 0px 30px 100px;
            font-size: 30px; 
            background:rgba(90,90,90,0.3);
            color: black;">

  <% if @lock %>
  
  <h1 class="show"><strong><%= @lock.name %></strong></h1>
  <p><strong>Website:</strong>&nbsp;&nbsp;&nbsp;<%= @lock.website %></p>
  <p><strong>Username:</strong>&nbsp;&nbsp;<%= @lock.username %></p>
  <p><strong>Password:</strong>&nbsp;&nbsp;<%= @lock.password %></p>
  <p><strong>Additional Info:</strong>&nbsp;&nbsp;<%=               @lock.additional_info %></p>
  <p><strong>Email linked with this account:</strong>&nbsp;&nbsp;<%= @lock.email_linked_with_this_account %></p>
  <p><strong> Kind:</strong>&nbsp;&nbsp;<%= @lock.kind.try(:name) %></p>
  
  <br>
  <br>
  <%= link_to " Back to account list", locks_path %>
 
<% else %>

  <p> Account  not  found </p>

<%end%>
</div>